theme: jekyll-theme-minimal

plugins:
  - jekyll-feed

title: Guanzhou Hu
description: Feeling comfortably numb

logo: /assets/img/Shark-sq.svg

resume_link: /assets/file/Resume_HGZ.pdf
linkedin_link: https://www.linkedin.com/in/josehu/
google_scholar_link: https://scholar.google.com/citations?hl=en&user=CXWO_egAAAAJ

email_one: guanzhou.hu (at) wisc.edu
email_two: josehu (at) cs.wisc.edu
