theme: jekyll-theme-minimal

title: Guanzhou (Jose) Hu
description: Guanzhou's personal storage for lecture notes, blog posts, & good mood.

logo: /assets/img/Shark-sq.svg

resume_link: /assets/file/Resume_HGZ.pdf
linkedin_link: https://www.linkedin.com/in/josehu/

email: guanzhou.hu (at) wisc (dot) edu
