# Theme.
[styles]
theme = "gruvbox"

# Layout.
[[row]]
ratio = 30
[[row.child]]
type = "cpu"
[[row]]
ratio = 70
[[row.child]]
ratio = 4
[[row.child.child]]
ratio = 3
type = "mem"
[[row.child.child]]
ratio = 5
type = "net"
[[row.child.child]]
ratio = 2
type = "temp"
[[row.child]]
ratio = 6
[[row.child.child]]
ratio = 7
type = "proc"
default = true
[[row.child.child]]
ratio = 3
type = "disk"
